[package]
name = "deep-learning"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
linear_transform = { path = "../linear_transform" }
num = { version = "0.4.0" }
hdf5 = { version = "0.8.1" }